CREATE TABLE `actions`
(
    `ID`          INT(11)      NOT NULL AUTO_INCREMENT,
    `COMMAND`     VARCHAR(50)  NOT NULL COLLATE 'utf8mb4_bin',
    `DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
    PRIMARY KEY (`ID`) USING BTREE,
    UNIQUE INDEX `COMMAND_UNIQUE` (`COMMAND`) USING BTREE
)
;
CREATE TABLE `questions`
(
    `ID`               INT(11)      NOT NULL AUTO_INCREMENT,
    `QUIZ_ID`          INT(11)      NOT NULL,
    `QUESTION_TEXT`    VARCHAR(255) NOT NULL DEFAULT '' COLLATE 'utf8mb4_bin',
    `ANSWER_TEXT`      VARCHAR(50)  NOT NULL DEFAULT '' COLLATE 'utf8mb4_bin',
    `ORDER_F`          INT(11)      NULL     DEFAULT '0',
    `DIFFICULTY_LEVEL` INT(11)      NULL     DEFAULT '0',
    PRIMARY KEY (`ID`) USING BTREE,
    INDEX `FK_questions_quiz` (`QUIZ_ID`) USING BTREE,
    CONSTRAINT `questions_ibfk_1` FOREIGN KEY (`QUIZ_ID`) REFERENCES `quiz` (`ID`) ON UPDATE CASCADE ON DELETE CASCADE
)
;
CREATE TABLE `questions_users_rel`
(
    `ID`          INT(11) NOT NULL AUTO_INCREMENT,
    `QUESTION_ID` INT(11) NOT NULL,
    `USER_ID`     INT(11) NOT NULL,
    `IS_CORRECT`  INT(11) NOT NULL,
    PRIMARY KEY (`ID`) USING BTREE,
    UNIQUE INDEX `USER_QUSTION_UNIQUE` (`USER_ID`, `QUESTION_ID`) USING BTREE,
    INDEX `FK__questions` (`QUESTION_ID`) USING BTREE,
    CONSTRAINT `FK__questions` FOREIGN KEY (`QUESTION_ID`) REFERENCES `questions` (`ID`) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `FK__users` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`ID`) ON UPDATE CASCADE ON DELETE CASCADE
)
;
CREATE TABLE `quiz`
(
    `ID`           INT(11)    NOT NULL AUTO_INCREMENT,
    `TITLE`        CHAR(50)   NOT NULL COLLATE 'utf8mb4_bin',
    `GRADE`        CHAR(11)   NOT NULL DEFAULT '0' COLLATE 'utf8mb4_bin',
    `CREATOR_ID`   INT(11)    NULL     DEFAULT '0',
    `CREATED_DATE` TIMESTAMP  NOT NULL,
    `HIDE_DATE`    TIMESTAMP  NULL     DEFAULT NULL,
    `IS_ACTIVE`    TINYINT(1) NOT NULL DEFAULT '1',
    PRIMARY KEY (`ID`) USING BTREE,
    INDEX `FK_quiz_users` (`CREATOR_ID`) USING BTREE,
    CONSTRAINT `quiz_ibfk_1` FOREIGN KEY (`CREATOR_ID`) REFERENCES `users` (`ID`) ON UPDATE CASCADE ON DELETE SET NULL
)
;
CREATE TABLE `quiz_users_rel`
(
    `ID`           INT(11)     NOT NULL AUTO_INCREMENT,
    `QUIZ_ID`      INT(11)     NOT NULL,
    `USER_ID`      INT(11)     NOT NULL,
    `START_DATE`   TIMESTAMP   NULL     DEFAULT NULL,
    `END_DATE`     TIMESTAMP   NULL     DEFAULT NULL,
    `SCORE_RESULT` VARCHAR(11) NOT NULL DEFAULT '0' COLLATE 'utf8mb4_bin',
    `QUIZ_GRADE`   INT(11)     NULL     DEFAULT NULL,
    PRIMARY KEY (`ID`) USING BTREE,
    UNIQUE INDEX `QUIZ_USER_UNIQUE_KEY` (`QUIZ_ID`, `USER_ID`) USING BTREE,
    INDEX `FK__users` (`USER_ID`) USING BTREE,
    CONSTRAINT `quiz_users_rel_ibfk_1` FOREIGN KEY (`QUIZ_ID`) REFERENCES `quiz` (`ID`) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `quiz_users_rel_ibfk_2` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`ID`) ON UPDATE CASCADE ON DELETE CASCADE
)
;
CREATE TABLE `users`
(
    `ID`                INT(11)    NOT NULL AUTO_INCREMENT,
    `USERNAME`          CHAR(50)   NOT NULL COLLATE 'utf8mb4_bin',
    `LOGIN`             CHAR(50)   NOT NULL COLLATE 'utf8mb4_bin',
    `PASSWORD`          CHAR(50)   NOT NULL COLLATE 'utf8mb4_bin',
    `IS_ACTIVE`         TINYINT(1) NOT NULL DEFAULT '1',
    `REGISTRATION_DATE` TIMESTAMP  NULL     DEFAULT NULL,
    `DEACTIVATION_DATE` TIMESTAMP  NULL     DEFAULT NULL,
    PRIMARY KEY (`ID`) USING BTREE,
    UNIQUE INDEX `USERNAME_KEY` (`USERNAME`) USING BTREE,
    UNIQUE INDEX `LOGIN_KEY` (`LOGIN`) USING BTREE
)
;
CREATE TABLE `users_activity`
(
    `ID`                   INT(11)    NOT NULL AUTO_INCREMENT,
    `USER_ID`              INT(11)    NOT NULL,
    `LAST_CONNECT_DATE`    TIMESTAMP  NULL     DEFAULT NULL,
    `LAST_DISCONNECT_DATE` TIMESTAMP  NULL     DEFAULT NULL,
    `KICK_DATE`            TIMESTAMP  NULL     DEFAULT NULL,
    `IS_ONLINE`            TINYINT(4) NOT NULL DEFAULT '0',
    PRIMARY KEY (`ID`) USING BTREE,
    UNIQUE INDEX `USER_ID_KEY` (`USER_ID`) USING BTREE,
    CONSTRAINT `FK_ONLINE_USERS_USERS` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`ID`) ON UPDATE CASCADE ON DELETE CASCADE
)
;
CREATE TABLE `user_roles`
(
    `ID`          INT(11)      NOT NULL AUTO_INCREMENT,
    `AUTH_ROLE`   VARCHAR(50)  NOT NULL COLLATE 'utf8mb4_bin',
    `DESCRIPTION` VARCHAR(255) NULL     DEFAULT NULL COLLATE 'utf8mb4_bin',
    `PRIORITY`    INT(11)      NOT NULL DEFAULT '0',
    PRIMARY KEY (`ID`) USING BTREE,
    UNIQUE INDEX `AUTH_ROLE_KEY` (`AUTH_ROLE`) USING BTREE
)
;
CREATE TABLE `users_user_roles_rel`
(
    `ID`           INT(11) NOT NULL AUTO_INCREMENT,
    `USER_ID`      INT(11) NOT NULL,
    `USER_ROLE_ID` INT(11) NOT NULL,
    PRIMARY KEY (`ID`) USING BTREE,
    INDEX `USER_ID_KEY` (`USER_ID`) USING BTREE,
    INDEX `FK_USER_ROLES_REL_USER_ROLES` (`USER_ROLE_ID`) USING BTREE,
    CONSTRAINT `FK_USER_ROLES_REL_USERS` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`ID`) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `FK_USER_ROLES_REL_USER_ROLES` FOREIGN KEY (`USER_ROLE_ID`) REFERENCES `user_roles` (`ID`) ON UPDATE RESTRICT ON DELETE RESTRICT
)
;
CREATE TABLE `user_roles_actions_rel`
(
    `ID`           INT(11) NOT NULL AUTO_INCREMENT,
    `USER_ROLE_ID` INT(11) NOT NULL,
    `ACTION_ID`    INT(11) NOT NULL,
    PRIMARY KEY (`ID`) USING BTREE,
    UNIQUE INDEX `ACTION_USER_ROLE_UNIQUE` (`ACTION_ID`, `USER_ROLE_ID`) USING BTREE,
    INDEX `FK_user_role_actions_rel_user_roles` (`USER_ROLE_ID`) USING BTREE,
    CONSTRAINT `FK_user_role_actions_rel_actions` FOREIGN KEY (`ACTION_ID`) REFERENCES `actions` (`ID`) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `FK_user_role_actions_rel_user_roles` FOREIGN KEY (`USER_ROLE_ID`) REFERENCES `user_roles` (`ID`) ON UPDATE CASCADE ON DELETE CASCADE
)
;